objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Est_Begin_Ship_Date__c</fullName>
        <inlineHelpText>Required to display this opportunity in phased reporting</inlineHelpText>
        <label>Est Begin Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Est_End_Ship_Date__c</fullName>
        <inlineHelpText>Required to display this opportunity in phased reporting</inlineHelpText>
        <label>Est End Ship Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PhasedShipments__c.object
<CustomObject>
    <description>for phasing opportunities</description>
    <fields>
        <fullName>Est_Disc_Sales__c</fullName>
        <label>Est Disc Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>PhasedOpps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_Date__c</fullName>
        <label>Ship Date</label>
        <type>Date</type>
    </fields>
    <label>PhasedShipment</label>
    <nameField>
        <label>Phased Shipments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PhasedShipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PhasedShipments.cls
public class PhasedShipments {

// 1. delete any existing shipments from PhasedShipments___c table
    
    public boolean deleteShipments(String OppId) {
        Boolean success = false;
        PhasedShipments__c[] ships = [SELECT Id, Opportunity__c
										FROM PhasedShipments__c
                                      	WHERE Opportunity__c = :OppId];
    
        //PhasedShipments__c ship = ships[0];
        //String oppId = ship.Opportunity__c;
    
        if (ships.size() > 0) {
           
            try {
                delete ships;
                success = true;
            } catch(System.DmlException e){
                success = false;
            }
        }
		return success;
    }

// 2. add new shipment records

    public boolean addShipments(String OppId) { 
        boolean success = false;
        // get the ship dates from the opp
        Opportunity[] ships = [SELECT Id, Amount, Est_Begin_Ship_Date__c, Est_End_Ship_Date__c
										FROM Opportunity
                                      	WHERE Id = :OppId];
    
        // calculate the # of months between the two
        if (ships.size() > 0) {
            Date beginShip = ships[0].Est_Begin_Ship_Date__c;
            Date endShip = ships[0].Est_End_Ship_Date__c;
            Integer shipments = beginShip.monthsBetween(endShip) + 1;
            
            // calculate the phased $ amount for each shipment
            Decimal phasedAmount = ships[0].Amount / shipments;
            
            // create new phasedShip records
        
            do {
                system.debug(beginShip.addMonths(shipments - 1));
                
                PhasedShipments__c[] newShipment = new PhasedShipments__c[0];
                try {
                  newShipment.add(new PhasedShipments__c(name = String.valueof(beginShip.addMonths(shipments - 1)),
                  Opportunity__c = ships[0].Id,
                  Ship_Date__c = beginShip.addMonths(shipments - 1),
                  Est_Disc_Sales__c = phasedAmount));
             
                  insert newShipment;
                  success = true;
                } catch (System.DmlException e) {
                    System.debug('ERROR: unable to create shipment: ' + e);
                    success = false;
                }
            
                
                shipments --;
            } while(shipments > 0);
        }
        return success;
    }
}